#List out names of restaurants or words commonly used

dessert <- c('cookie','cake','dough','cream','milk')
thai <- c('thai','tara temple')
salad_healthy <- c('green','leaf', 'little beet','leon','hipcity')
korean <- c('seoul','korean','bibimix')
italian <- c('pizza', 'focacc','trattoria')
mexican <- c('salsa l','rito loco','el chucho','mex','taco','pollo','guapo','burrito','cielo','laredo','tortilla','dulcinea')
japanese <- c('iron chef','passion fin','maneki neko','buredo','japan','sushi','asia','hibachi','sakana','donburi')
american <-c('little beast','galaxie','lost dog','Mid Atlantic Seafood','southwest','soul','medium rare','wings','burger','popeyes','chicken','rooster','bbq','hill country', 'jersey','donald','oklahoma','just wing it')
vietnamese <-c('banh','viet','pho','sprig','rice paddies')
mediterranean <-c('fresh med','munch','zaytin','mediterr','acac','meat in a box','cava','yafa','m - Dupont Circle')
indian <- c('india','lalig','masala')
salvadoran <- c('tamar','judy','pupuseria')
middle_eastern <-c('shouk','george','Halal Guys','Shawafel','north beach gyros')
chinese <-c('chinese','dumpl','bao','china', 'tony cheng','Jerry’s Carry Out')
hawaiian <- c('poki','poke')
juice <-c('robek','smoothie')
israeli <-c('shouk')
peruvian <-c('rico', 'Crisp and Juicy - Tenleytown')
ethiopian <-c('zenebe','ethio')
chinese_korean <-c('chiko')
bangladeshi <- c('gharer')
greek <-c('souvlaki','greek')
south_african <- c('nando')
bakery <- c('bread furst','bagel')
afghan <-c('Maiwand Grill')
latin <-c('panas')
